### PR TITLE
Add PR for Vue.js 3 + Vite test demo

### PR DESCRIPTION
**Pull request by sophiebremer**
Based on PR #30 by @pcccccc

### CODE REVIEW

**Comment by sophiebremer** [comment]
Thank you for your contribution, @pcccccc!

Please review the final merge. Let me know, if the name in the AUTHORS.md should be modified (or removed).

**Comment by pcccccc** [comment]
Hello, I have checked and it's running normally. Could you provide me with the table structure for iCloud.org.netzkonform.CloudKitTS? I'd like to continue improving the insert, select, update, delete functionality in the demo.

**Comment by sophiebremer** [comment]
Hello, thank for the review!

A full demo goes beyond the goal of this package. The container is empty without any records. It just exists to test that Apple's code matches the TypeScript declarations and runs.

You might consider creating a Vue boiler plate repository, that can be linked from the readme file in this package.

BTW Apple has created it's own demo for CloudKit JS:
* Download code: https://developer.apple.com/library/archive/samplecode/CloudAtlas/Introduction/Intro.html

* Live code: https://cdn.apple-cloudkit.com/cloudkit-catalog/

**Comment by pcccccc** [comment]
> Hello, thank for the review!
> 
> A full demo goes beyond the goal of this package. The container is empty without any records. It just exists to test that Apple's code matches the TypeScript declarations and runs.
> 
> You might consider creating a Vue boiler plate repository, that can be linked from the readme file in this package.
> 
> BTW Apple has created it's own demo for CloudKit JS:
> 
> * Download code: https://developer.apple.com/library/archive/samplecode/CloudAtlas/Introduction/Intro.html
> * Live code: https://cdn.apple-cloudkit.com/cloudkit-catalog/

OK, Thank you

**Comment by sophiebremer** [comment]
Thank you for your contribution!

**Pull request merged**
