### PR TITLE
Add vue3+vite demo

### PR DESCRIPTION
**Pull request by pcccccc**
add vue3+vite demo

The README.md contains a more detailed usage guide.

### CODE REVIEW

**Comment by sophiebremer** [comment]
Hello @pcccccc!
Thank you for the demo PR. I will test it this or next weekend. One question that comes to my mind when just scanning the new files: Are Vite and Volar necessities for the Vue demo to work?

**Comment by pcccccc** [comment]
> Hello @pcccccc! Thank you for the demo PR. I will test it this or next weekend. One question that comes to my mind when just scanning the new files: Are Vite and Volar necessities for the Vue demo to work?

Hello! When creating a Vue3 project, I chose Vite as the default build tool.

Vue3 officially recommends Vite as a build tool due to its excellent development experience
The Vue team participated in Vite's development, ensuring good integration with Vue3
Using Vite makes it easier to set up and develop Vue3 projects, but it's not mandatory
Alternatives:
If you don't use Vite, you can still use other tools to develop Vue3 projects, such as:

· Vue CLI
· webpack
· Rollup
· Parcel

**Comment by pcccccc** [comment]
volar should be a dependency of other packages.

**Comment by sophiebremer** [comment]
So Vite is kind of the default for Vue. Thank you for the explanation.

**Pull request merged**
